### ISSUE TITLE
Publish these types in @types scope on npm

### ISSUE THREAD

**Issue by 0x203** [swissspidy/typed-swagger-tools#1]
With the release of [Typescript 2](https://blogs.msdn.microsoft.com/typescript/2016/09/22/announcing-typescript-2-0/) it is possible to install types only using `npm`, no `tsd` or `typings` needed.

Du you mind publishing these types here in a way that they are available in the `@types` scope on npm? As far as I found out, this means publishing them in the [DefinitlyTyped repo](/DefinitelyTyped/DefinitelyTyped) so they can be published by the [Microsoft types publisher](/Microsoft/types-publisher), but there may be a more simple way.

Thank you for your efforts!

**Comment by swissspidy** [comment]
Hey there,

Thanks for your request! I'm not using swagger-tools anymore, but I'm happy to add these definitions to DefinitelyTyped (probably together with some renaming). Until then, you can also reference them via GitHub:

```
typings install github:swissspidy/typed-swagger-tools#5fb3f2956a1a3aaae4fe3158b75e665068e631ff
```

**Comment by 0x203** [comment]
Cool, thank you!

**Comment by ghost** [comment]
If this project is abandoned, I am willing to take over a fork and submit it to DefTyped ... Until then, a good way to use these types might be a dependency like this:

```
  "@types/swagger-tools": "jzorn/typed-swagger-tools"
```

**Comment by swissspidy** [comment]
@jzorn Sounds great!

**Comment by ghost** [comment]
Great! Do you want to put up a deprecation note and link to the new repository?

**Comment by swissspidy** [comment]
Sure, I'll update the readme. Thanks for taking over!
